# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=254)),
                ('full_name', models.CharField(default='', max_length=60)),
                ('street_Address1', models.CharField(default='', max_length=40)),
                ('street_Address2', models.CharField(default='', max_length=40)),
                ('town_or_city', models.CharField(default='', max_length=40)),
                ('county', models.CharField(default='', max_length=40)),
                ('country', models.CharField(default='', max_length=40)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
