# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-26 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='era',
            field=models.CharField(choices=[('AD', 'AD'), ('BC', 'BC')], max_length=2),
        ),
    ]
