# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-17 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_artefact_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='current_bid',
        ),
    ]
