# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0002_auto_20190926_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='era',
            field=models.CharField(choices=[('AD', 'Anno Domini'), ('BC', 'Before Christ')], max_length=2),
        ),
    ]
