# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-16 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('del_full_name', models.CharField(max_length=60)),
                ('del_street_address1', models.CharField(max_length=40)),
                ('del_street_address2', models.CharField(max_length=40)),
                ('del_town_or_city', models.CharField(max_length=40)),
                ('del_county', models.CharField(max_length=40)),
                ('del_country', models.CharField(max_length=40)),
                ('del_postcode', models.CharField(blank=True, max_length=20)),
                ('del_phone_number', models.CharField(max_length=20)),
                ('del_email', models.CharField(max_length=254)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artefacts.Artefact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
            ],
        ),
    ]
