# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0004_auto_20191013_2013'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artefacts.Customer'),
            preserve_default=False,
        ),
    ]
