# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_name', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
