# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Current_Bid',
        ),
    ]
