# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20191012_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBidsgit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_name', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Current_Bid',
        ),
    ]
