# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-12 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20191012_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllBidsgit',
            new_name='AllBids',
        ),
    ]
